import logging
from typing import Optional

import jieba
from pymilvus import MilvusClient, DataType, Function, FunctionType, AnnSearchRequest, RRFRanker

from app.services.schema import VectorDatabaseData, SourceData

jieba.setLogLevel(20)
logger = logging.getLogger(__name__)

class MilvusManager:
    def __init__(
        self, 
        url: str, 
        collection_name: str, 
        embedding_dim: int
    ) -> None:
        """Initialize the lancedb client.
        Args:
            url (str): The url of the lancedb server or local path.
            collection_name (str): The name of the collection.
            embedding_dim (int): The dimension of the embedding.
        """
        self.client = MilvusClient(uri=url, token="root:Milvus", db_name="default")
        self.collection_name = collection_name
        self.embedding_dim = embedding_dim

    def _get_filter(
        self, 
        card_id: Optional[str] = None,
        bank_code: Optional[str] = None
    ) -> Optional[str]:
        """Get the filter string for the query.
        Args:
            card_id (str | None): The card id.
            bank_code (str | None): The bank code.
        Returns:
            The filter string.
        """
        filters = []
        if card_id and card_id.strip():
            filters.append(f"card_id == '{card_id.strip()}'")
        if bank_code and bank_code.strip():
            filters.append(f"bank_code == '{bank_code.strip()}'")
        return " AND ".join(filters) if filters else None
    
    def create_collection(
        self, 
        overwrite: bool = False
    ) -> None:
        """Create the collection.
        Args:
            overwrite (bool): Whether to overwrite the collection.
        """
        if overwrite and self.client.has_collection(self.collection_name):
            self.client.drop_collection(self.collection_name)
            logger.info(f"Collection {self.collection_name} dropped.")

        if not self.client.has_collection(self.collection_name):
            # create schema
            schema = MilvusClient.create_schema(auto_id=True)
            schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True, description="document id")
            schema.add_field(field_name="text", datatype=DataType.VARCHAR, max_length=65535, enable_analyzer=True, analyzer_params={"type": "chinese"}, description="raw text of document description")
            schema.add_field(field_name="text_dense", datatype=DataType.FLOAT_VECTOR, dim=self.embedding_dim, description="text dense embedding")
            schema.add_field(field_name="text_sparse", datatype=DataType.SPARSE_FLOAT_VECTOR, description="text sparse embedding auto-generated by the built-in BM25 function")
            schema.add_field(field_name="url", datatype=DataType.VARCHAR, max_length=512)
            schema.add_field(field_name="card_id", datatype=DataType.VARCHAR, max_length=128)
            schema.add_field(field_name="card_name", datatype=DataType.VARCHAR, max_length=32)
            schema.add_field(field_name="bank_code", datatype=DataType.VARCHAR, max_length=32)
            
            # add BM25 function to schema
            bm25_function = Function(
                name="text_bm25_emb",
                input_field_names=["text"],
                output_field_names=["text_sparse"],
                function_type=FunctionType.BM25,
            )
            schema.add_function(bm25_function)

            # create index
            index_params = self.client.prepare_index_params()
            index_params.add_index(
                field_name="text_dense",
                index_name="text_dense_index",
                index_type="AUTOINDEX",
                metric_type="IP"
            )

            index_params.add_index(
                field_name="text_sparse",
                index_name="text_sparse_index",
                index_type="SPARSE_INVERTED_INDEX",
                metric_type="BM25",
                params={"inverted_index_algo": "DAAT_MAXSCORE"}, # or "DAAT_WAND" or "TAAT_NAIVE"
            )

            index_params.add_index(
                field_name="card_id",
                index_name="card_id_index",
                index_type="AUTOINDEX",
            )

            index_params.add_index(
                field_name="bank_code",
                index_name="bank_code_index",
                index_type="AUTOINDEX",
            )

            # create collection
            self.client.create_collection(
                collection_name=self.collection_name,
                schema=schema,
                index_params=index_params
            )

            logger.info(f"Collection `{self.collection_name}` created.")

    def insert(
        self,
        data: list[VectorDatabaseData]
    ) -> None:
        """Insert data into the Milvus collection.
        Args:
            data (list[VectorDatabaseData]): The data to insert.
        """
        res = self.client.insert(
            collection_name=self.collection_name,
            data=[
                {
                    "text": item.text,
                    "text_dense": item.vector,
                    "url": item.url,
                    "card_id": item.card_id,
                    "card_name": item.card_name,
                    "bank_code": item.bank_code
                }
                for item in data
            ]
        )
        logger.info(f"Successfully inserted {res['insert_count']} documents to collection {self.collection_name}.")

    def delete(
        self,
        key: str,
        value: str
    ) -> None:
        """Delete the data with the specified key and value from the Milvus collection.
        Args:
            key (str): The key of the row to be deleted.
            value (str): The value of the row to be deleted.
        """
        res = self.client.delete(
            collection_name=self.collection_name,
            filter=f'{key} == "{value}"'
        )
        logger.info(f"Successfully deleted {res['delete_count']} documents from collection {self.collection_name}.")

    def hybrid_search(
        self, 
        query: str, 
        query_vector:list[float], 
        card_id: Optional[str] = None,
        bank_code: Optional[str] = None,
        reranker: bool = False,
        top_k: int = 10, 
    ) -> list[SourceData]:
        """Hybrid search with text semantic search (dense) and full-text search (sparse).
        Args:
            query (str): The text used to search for relevant answers.
            query_vector (list[float]): The vector representation of the query, used for searching relevant answers. This vector should be computed from the query.
            reranker (bool): Indicates whether to use a reranking system to improve accuracy.
            top_k (int): The number of results to return.
        Returns:
            list[SourceData]: The search results are returned in order of relevance, from highest to lowest.
        """
        # text semantic search (dense)
        search_param_1 = {
            "data": [query_vector],
            "anns_field": "text_dense",
            "param": {"nprobe": 10},
            "expr": self._get_filter(card_id, bank_code),
            "limit": top_k
        }
        request_1 = AnnSearchRequest(**search_param_1)

        # full-text search (sparse)
        search_param_2 = {
            "data": [query],
            "anns_field": "text_sparse",
            "param": {"drop_ratio_search": 0.2},
            "expr": self._get_filter(card_id, bank_code),
            "limit": top_k
        }
        request_2 = AnnSearchRequest(**search_param_2)

        res = self.client.hybrid_search(
            collection_name=self.collection_name,
            reqs=[request_1, request_2],
            ranker=RRFRanker(top_k*2) if reranker else None,
            limit=top_k,
            output_fields=["text", "url", "card_id", "card_name", "bank_code"]
        )

        sources: list[SourceData] = []
        for hits in res:
            for hit in hits:
                sources.append(SourceData(
                    text=hit.entity.text,
                    url=hit.entity.url,
                    card_id=hit.entity.card_id,
                    card_name=hit.entity.card_name,
                    bank_code=hit.entity.bank_code
                ))
        
        return sources
    
    def close(self):
        self.client.close()