bank_code: cathaybk
bank_name: 國泰世華
is_dynamic: true
xpaths:
  tab_link:
  division: //div[@data-ga-card="true"]
  card:
    title: .//h3/text()
    url: .//a[contains(@title, "信用卡介紹-詳細說明")]//@href
features:
  - card_code: cube
    cookie_button:
    focus:
      - content:
        link:
    sub_focus_content:
      - //ol[@class="w-full"]//li[@class="group is-active"]//div[contains(@class, "box-border")]
    close_button: //div[@id='modal-popup'][contains(@class, 'modal-popup-active')]//div[contains(@class, "cursor-pointer")] | //li[@class="group is-active"]
