bank_code: entiebank
bank_name: 安泰銀行
is_dynamic: True
xpaths:
  tab_link:
  division: //div[contains(@class, "card vertical") or contains(@class, "card horizontal")]
  card:
    title: ./div[@class="cardTitle"]/text()
    url: ./a/@href
features:
  - card_code: test
    cookie_button:
    focus:
      - content:
        link:
    sub_focus_content:
    close_button:
