bank_code: fubon
bank_name: 台北富邦銀行
is_dynamic: False
xpaths:
  tab_link:
  division: //div[@class="card-list-box"]
  card:
    title: .//p[@class="card-title"]/text()
    url: .//a[@class="more-btn"]/@href
features:
  - card_code: test
    cookie_button:
    focus:
      - content:
        link:
    sub_focus_content:
    close_button:
