bank_code: obank
bank_name: 王道銀行
is_dynamic: True
xpaths:
  tab_link: //*[contains(@id, "layout_0_lv_Sidebar_Landings_lnkLanding")]
  skip_card_tabs:
    - 簽帳金融卡: /retail/debit/cardmain_new
  division: //div[@class="n-table-medium"][.//a[text()="詳細活動內容" or text()="了解更多"]]
  card:
    title: .//h4/text()
    url: .//a[text()="詳細活動內容" or text()="了解更多"]/@href
features:
  - card_code: test
    cookie_button:
    focus:
      - content:
        link:
    sub_focus_content:
    close_button:
