"""baseline: cards, crawl_jobs, card_chunks, summary_cache

Revision ID: bb668488f8ae
Revises: 
Create Date: 2026-08-09 02:09:21.467388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb668488f8ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_chunks',
    sa.Column('card_key', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('page_url', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('card_key', 'seq')
    )
    with op.batch_alter_table('card_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_chunks_content_hash'), ['content_hash'], unique=False)

    op.create_table('cards',
    sa.Column('card_key', sa.String(length=40), nullable=False),
    sa.Column('bank_code', sa.String(length=32), nullable=False),
    sa.Column('card_name', sa.String(length=128), nullable=False),
    sa.Column('card_url', sa.String(length=1024), nullable=False),
    sa.Column('facts_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('card_key'),
    sa.UniqueConstraint('card_url')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_bank_code'), ['bank_code'], unique=False)

    op.create_table('crawl_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('bank_code', sa.String(length=32), nullable=False),
    sa.Column('card_key', sa.String(length=40), nullable=True),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('artifact_dir', sa.String(length=512), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('callback_url', sa.String(length=1024), nullable=True),
    sa.Column('callback_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_card_status', ['card_key', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_jobs_status'), ['status'], unique=False)

    op.create_table('summary_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_ver', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', 'model_name', 'prompt_ver')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_cache')
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_batch_id'))
        batch_op.drop_index('idx_jobs_card_status')

    op.drop_table('crawl_jobs')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_bank_code'))

    op.drop_table('cards')
    with op.batch_alter_table('card_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_chunks_content_hash'))

    op.drop_table('card_chunks')
    # ### end Alembic commands ###
