banks:
  - bank_code: taishin
    bank_name: 台新銀行
    is_dynamic: False
    xpaths:
      # if no tab or division, no need to fill in
      tab_link: //ul[@class="nav nav-tabs  tab-sty-1"]/li/a/@href
      division: .//li[@class="ul-li-items" and @itemprop="itemListElement"]
      card:
        title: .//p[@itemprop="name"]/text()
        url: .//a[@itemprop="url"]/@href
        # If necessary, add more xpath to avoid matching without results
        content:
          - //*[@id="centercontainer"]/div
  
  - bank_code: dbs
    bank_name: 星展銀行
    is_dynamic: False
    xpaths:
      tab_link: 
      division: .//div[@data-card]
      card:
        title: ./div/div/div[1]//text()
        url: ./div/div/div[1]//@href
        content: 
          - ""
  
  - bank_code: cathaybk
    bank_name: 國泰世華
    is_dynamic: False
    xpaths:
      tab_link: 
      division: //div[@class="cubre-m-compareCard -credit"]
      card:
        title: .//div[@class='cubre-m-compareCard__title']/text()
        url: .//div[@class="cubre-m-compareCard__link"]//@href
        content: 
          - ""

  - bank_code: sinopac
    bank_name: 永豐銀行
    is_dynamic: False
    xpaths:
      tab_link: //h2[normalize-space(text())="卡片總覽"]/parent::li/ul[@class="lv2"]/li/a/@href
      division: //ul[@class="Ltype1 cf"]/li
      card:
        title: ./h2/a/text()
        url: ./h2/a/@href
        content: 
          - ""

  - bank_code: fubon
    bank_name: 台北富邦銀行
    is_dynamic: False
    xpaths:
      tab_link: 
      division: //li[@class="credit-card"]
      card:
        title: ./div[@class="title"]/text()
        url: ./a[span[normalize-space(text())="了解更多"]]/@href
        content: 
          - ""

  - bank_code: esunbank
    bank_name: 玉山銀行
    is_dynamic: False
    xpaths:
      tab_link: 
      division: //div[@data-cardattr]
      card:
        title: .//h3[@class="l-card__title"]/text()
        url: ./a/@href
        content: 
          - ""

  - bank_code: hsbc
    bank_name: 滙豐銀行
    is_dynamic: False
    xpaths:
      tab_link: 
      division: //div[@class="productModule"]
      card:
        title: .//*[contains(@class, "A-LNKND38L-RW-ALL")]/text()
        url: .//a[@class="A-BTNSO-RW-ALL"]/@href
        content: 
          - ""

  - bank_code: ctbcbank
    bank_name: 中國信託
    is_dynamic: True
    xpaths:
      tab_link: //a[contains(@class, "twrbo-c-filterOption")]
      division: //li[@class="twrbc-creditcard-list-item"]
      card:
        title: .//a[@class="twrbc-creditcard-title"]/text()
        url: .//div[@class="twrbc-creditcard-tools"]/a/@href
        content: 
          - ""
    
  - bank_code: firstbank
    bank_name: 第一銀行
    is_dynamic: False
    xpaths:
      tab_link: 
      division: //div[contains(@class, "card-item")]
      card:
        title: .//strong/text()
        url: .//a[1]/@href
        content: 
          - ""

  - bank_code: feib
    bank_name: 遠東商銀
    is_dynamic: False
    xpaths:
      tab_link: 
      division: //div[contains(@class, "carousel-item")]
      card:
        title: ./h2/text()
        url: ./a/@href
        content: 
          - ""

  - bank_code: rakuten
    bank_name: 台灣樂天
    is_dynamic: True
    xpaths:
      tab_link: //div[@id="navCampaign"]//a
      division: '//div[@style="display: block;"]'
      card:
        title: //div[@id="navCampaign"]//a[@class="active"]/text()
        url: .//a[@class="btnApply_b"]/@href
        content: 
          - ""

  - bank_code: americanexpress
    bank_name: 美國運通
    is_dynamic: True
    xpaths:
      tab_link: //button[contains(@class, "sc_mo_carousel-card-tabs_item")]
      division: //div[contains(@class, "sc_at_box_root")]//div[@data-qe-id="HorizontalCardTile"]
      card:
        title: .//div[contains(@class, "sc_fontType_helvetica_bold")]/text()
        url: .//a[contains(@class, "sc_horizontallyFluid")]/@href
        content: 
          - ""

  - bank_code: ubot
    bank_name: 聯邦銀行
    is_dynamic: True
    xpaths:
      tab_link: //div[@class="accordion-body"]//a[@aria-current="page"]
      division: //div[@class="cardDiv"]
      card:
        title: .//a/h2/text()
        url: .//button[@class="btn buttonMore"]/../@href
        content: 
          - ""

  - bank_code: yuantabank
    bank_name: 元大銀行
    is_dynamic: False
    xpaths:
      tab_link:
      division: //div[@class="card_items"]//li
      card:
        title: ./div[@class="card_name"]//text()
        url: ./a/@href
        content: 
          - ""