banks:
  - bank_code: taishin
    bank_name: 台新銀行
    xpaths:
      # if no tab or division, no need to fill in
      tab_link: //ul[@class="nav nav-tabs  tab-sty-1"]/li/a/@href
      division: .//li[@class="ul-li-items" and @itemprop="itemListElement"]
      card:
        title: .//p[@itemprop="name"]/text()
        url: .//a[@itemprop="url"]/@href
        # If necessary, add more xpath to avoid matching without results
        content:
          - //*[@id="centercontainer"]/div
  
  - bank_code: dbs
    bank_name: 星展銀行
    xpaths:
      tab_link: 
      division: .//div[@data-card]
      card:
        title: ./div/div/div[1]//text()
        url: ./div/div/div[1]//@href
        content: 
          - ""
